### ISSUE TITLE
Can't use keyboard buttons to switch song or pause

### ISSUE THREAD

**Issue by jhartmann44** [cross-platform/apple-music-for-linux#35] opened 2021-10-27 08:21 UTC
When I try to skip to the next song it won't do it, same thing with pausing.
When I use Apple Music in Chrome I can switch and pause songs.
I'm using Ubuntu 20.04 and the newest version of apple-music-for-linux

**Comment by MarcusTomlinson** [comment] 2021-11-10 08:18
Duplicate of https://github.com/cross-platform/apple-music-for-linux/issues/8

**Closed by MarcusTomlinson** 2021-11-10 08:18 UTC
