### ISSUE TITLE
Flatpak version please

### ISSUE THREAD

**Issue by CHJ85** [cross-platform/apple-music-for-linux#20] opened 2020-12-10 10:08 UTC
Hi there. I really do not want to use Snap. Way too sluggish and also I'm not comfortable with the fact of its backend being proprietary.

**Comment by MarcusTomlinson** [comment] 2020-12-10 10:36
Duplicate of https://github.com/cross-platform/apple-music-for-linux/issues/10

**Closed by MarcusTomlinson** 2020-12-10 10:36 UTC
