### ISSUE TITLE
Make a Flatpak build!

### ISSUE THREAD

**Issue by marc-mader00** [cross-platform/apple-music-for-linux#22] opened 2021-02-12 18:42 UTC
I would like to have a flatpak version of this app as an iPhone user, as the popritary does not like snap and canoncial.

**Comment by MarcusTomlinson** [comment] 2021-02-12 18:45
Duplicate of https://github.com/cross-platform/apple-music-for-linux/issues/10

**Closed by MarcusTomlinson** 2021-02-12 18:45 UTC
